name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install packages
        run: npm i
      - name: Set Creds
        run: git config user.name "ilon-mars" && git config user.email "ilon.mars@yandex.ru"
      - name: Deploy
        run: npm run deploy
